import { Link } from "react-router-dom";
import "./10.1.css";
import { MathComponent } from "mathjax-react";

export default function Calculus2_Ch10_Sec1() {
    
    
    return (
        <div className='container'> 
        <h1>Ch. 10 Sec. 1 An Overview</h1>
        <div className="sectionText">

      <h2>Sequence</h2>
      <div className="textBorder">
       <p>
        A <b>sequence </b><MathComponent tex="{a_{n}}" /> is an ordered list of numbers of the form
       </p>
        <MathComponent tex="{a_{1},a_{2},a_{3},...,a_{n},...}." />
        <p>
            A sequence may be generated by a recurrence relation of the form <MathComponent tex="a_{n+1} = f(a_{n})," />
            for n = 1,2,3,..., where <MathComponent tex="a_{1}" /> is given. A sequence may also be defined with an explicit formula of the 
            form <MathComponent tex="a_{n} = f(n), \hspace{.2cm} \mathrm{for \hspace{.2cm} n = 1,2,3,....}" />
        </p>
        *358
      </div>


      <h2>Limit of a Sequence</h2>
      <p className="textBorder">
       <p>
        If the terms of a sequence <MathComponent tex="{a_{n}}" /> approaches a unique number L as n increases, that is, if
        <MathComponent tex="a_{n}" /> can be made arbitrarily close to L by taking n sufficiently large, then we say 
        <MathComponent tex="\lim_{n\to \infty} \hspace{.2cm} a_{n} = L" /> exists, and the sequence converges to L. If the terms of the
        sequence do not approach a single number as n increases, the sequence has no limit, and the sequence diverges.
       </p>
        
        *359
      </p>


      <h2>Infinite Series</h2>
      <p className="textBorder">
       <p>
        Given a sequence <MathComponent tex="{a_{1}, a_{2}, a_{3}, ... }," /> the sum of its terms
        <MathComponent tex="a_{1} + a_{2} + a_{3} + ... = \sum_{k=1}^{\infty} a_{k}" /> is called an
        infinite series. The sequence of partial sums <MathComponent tex="{S_{n}}" /> associated with this series
        has the terms
       </p>
        <MathComponent tex="S_{1} = a_{1}" />
        <MathComponent tex="S_{2} = a_{1} + a_{2}" />
        <MathComponent tex="S_{3} = a_{1} + a_{2} + a_{3}" />
        <MathComponent tex="\vdots" />
        <MathComponent tex="S_{n} = a_{1} + a_{2} + a_{3} + ... + a_{n} = \sum_{k=1}^{n} a_{k}, \hspace{.2cm} \mathrm{for \hspace{.15cm} n =1,2,3,....}" />
        <p>
            If the sequence of partial sums <MathComponent tex="{S_{n}}" /> has a limit L, the infinite series converges to that limit, and we write
        </p>
        <MathComponent tex="\sum_{k=1}^{\infty} a_{k} = \lim_{n\to \infty} \sum_{k=1}^{n} a_{k} = \lim_{n\to \infty} S_{n} = L" />
        <p>
            If the sequence of partial sums diverges, the infinite series also diverges.
        </p>
        *360
      </p>
      

      



            </div>


            <h1>Examples</h1>
            <div className="examples"> 
            <div className="Example-1">
                    <h3>Example 1</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-2">
                    <h3>Example 2</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-3">
                    <h3>Example 3</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-4">
                    <h3>Example 4</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-5">
                    <h3>Example 5</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>




            </div>
            </div>
           
    );
}