import { Link } from "react-router-dom";
import "./1.6.css";
import { MathComponent } from "mathjax-react";

export default function ModernAlgebra_Part1_Sec6() {
    
    
    return (
        <div className='container'> 
        <h1>Part 1 Section 6 Cyclic Groups</h1>
        <div className="sectionText">

      
      <h2>6.1 Theorem</h2>
      <p className="textBorder">
       
       <p>Every cyclic group is abelian.</p>
        *42
      </p>


      <h2>6.2 Division Algorithm for Z</h2>
      <p className="textBorder">
       <p>If m is a positive integer and n is any integer, then there exist unique integers q and r such that</p>
        <MathComponent tex="\mathrm{n = mq + r \hspace{2cm} and \hspace{2cm} 0 \leq r \leq m.}" />
        *43
      </p>


      <h2>6.6 Theorem</h2>
      <p className="textBorder">
       
        <p>A subgroup of a cyclic group is cyclic.</p>
        *44
      </p>


      <h2>6.7 Corollary</h2>
      <p className="textBorder">
       
        <MathComponent tex="\mathrm{The \hspace{.2cm} subgroups \hspace{.2cm} of \hspace{.2cm} Z \hspace{.2cm}under \hspace{.2cm} addition \hspace{.2cm} are \hspace{.2cm} precisely \hspace{.2cm} the \hspace{.2cm} groups \hspace{.2cm} nZ \hspace{.2cm} under \hspace{.2cm} addition \hspace{.2cm} for \hspace{.2cm} n \in Z.}" />.
        *45
      </p>


      <h2>6.8 Definition</h2>
      <p className="textBorder">
       <p>Let r be a positive integer and s be a non-negative integer. The positive generator d of the cyclic group</p>
        <MathComponent tex="\mathrm{H = \{nr + ms | \hspace{.2cm} n,m \in Z \}}" />
        <p>under addition is the greatest common divisor (abbreviated gcd) of r and s. We write d = gcd(r, s).</p>
        *46
      </p>


      <h2>6.10 Theorem</h2>
      <p className="textBorder">
       <p>Let G be a cyclic group with generator a.</p>
        <MathComponent tex="\mathrm{If \hspace{.2cm} the \hspace{.2cm} order \hspace{.2cm} of \hspace{.2cm} G \hspace{.2cm} is \hspace{.2cm} infinite, \hspace{.2cm} then \hspace{.2cm} G \hspace{.2cm} is \hspace{.2cm} isomorphic \hspace{.2cm} to \hspace{.2cm} \langle Z, + \rangle .}" />
        <MathComponent tex="\mathrm{If \hspace{.2cm} G \hspace{.2cm} has \hspace{.2cm} finite \hspace{.2cm} order \hspace{.2cm} n, \hspace{.2cm} then \hspace{.2cm} G \hspace{.2cm} is \hspace{.2cm} isomorphic \hspace{.2cm}to \hspace{.2cm} \langle Z_{n}, +_{n} \rangle .}" />
        *47
      </p>


      <h2>6.15 Theorem</h2>
      <p className="textBorder">
       <p>Let G be a cyclic group with n elements and generated by a.</p>
        <MathComponent tex="\mathrm{Let \hspace{.2cm} b \in G \hspace{.2cm} and \hspace{.2cm} let \hspace{.2cm} b = a^{s}.}" />
        <p>Then b generates a cyclic subgroup H of G containing n/d elements, where d is the greatest common divisor of n and s.</p>
        <MathComponent tex="\mathrm{Also, \hspace{.2cm} \langle a^{s} \rangle = \langle a^{t} \rangle \hspace{.2cm} if \hspace{.2cm} and \hspace{.2cm} only \hspace{.2cm} if \hspace{.2cm} gcd(s,n) = gcd(t,n).}" />
        *48
      </p>


      <h2>6.17 Corollary</h2>
      <p className="textBorder">
       <p>If a is a generator of a finite cyclic group G of order n, then the other generators of G are the elements of the form</p>
        <MathComponent tex="\mathrm{a^{r}, \hspace{.2cm} where \hspace{.2cm} r \hspace{.2cm} is \hspace{.2cm} relatively \hspace{.2cm} prime \hspace{.2cm} to \hspace{.2cm} n.}" />.
        *49
      </p>


      <h2>6.20 Corollary</h2>
      <p className="textBorder">
       
        <MathComponent tex="\mathrm{Let \hspace{.2cm} G \hspace{.2cm} be \hspace{.2cm} a \hspace{.2cm} finite \hspace{.2cm} cyclic \hspace{.2cm} group \hspace{.2cm} and \hspace{.2cm} H \leq G.}" />
        <MathComponent tex="\mathrm{Then \hspace{.2cm} |H| \hspace{.2cm} divides \hspace{.2cm} |G|. \hspace{.2cm} That \hspace{.2cm} is, \hspace{.2cm}|G| \hspace{.2cm} is \hspace{.2cm} a \hspace{.2cm} multiple \hspace{.2cm} of \hspace{.2cm} |H|.}" />
        *50
      </p>
      



            </div>


            <h1>Examples</h1>
            <div className="examples"> 
            <div className="Example-1">
                    <h3>Example 1</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-2">
                    <h3>Example 2</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-3">
                    <h3>Example 3</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-4">
                    <h3>Example 4</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>


                <div className="Example-5">
                    <h3>Example 5</h3>
                    <div className="textBorder">
                      <h4></h4>
                      <p>
                        
                      </p>
                      
                     
                    <p>
                        Answer: <br/>
                         <MathComponent tex="" />    
                         
                    </p>

                    *
                    </div>
                </div>




            </div>
            </div>
           
    );
}